// Copyright 2025 the UI Events Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

use dpi::PhysicalPosition;

/// Scroll delta.
///
/// Deltas are in a Y-down coordinate system, and represent a ‘navigation’
/// direction; a positive Y value means that the viewport should move downward
/// relative to the content.
///
/// For mouse wheel events, only `LineDelta` and `PixelDelta` are typical.
/// For scroll deltas generated by scrollbars or other elements, `PageDelta`
/// may be used (for example, when clicking in the well of the scrollbar).
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ScrollDelta {
    /// Page delta.
    ///
    /// Page deltas are almost always synthetic, typically generated by clicking
    /// in the well of a scrollbar.
    PageDelta(f32, f32),
    /// Line delta.
    LineDelta(f32, f32),
    /// Pixel delta.
    PixelDelta(PhysicalPosition<f64>),
}
